pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat 'C:\\maven\\bin\\mvn.cmd -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                bat "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
        stage('Start Tomcat Docker Image'){
            steps {
                bat "docker run -d -p 9090:8080 tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
    }
}
