pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat "C:\\maven\\bin\\mvn.cmd -f java-tomcat-sample/pom.xml clean package"
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_app_stg_pipeline'

            }
            
        }
    }
}
